### ISSUE TITLE
Question on gdb

### ISSUE THREAD

**Issue by mingwayzhang** [kpouget/tuto-gdb.py#1]
Hi Kevin ,

It was good to look at your gdb related blogs and it really helped me a lot.

So, i have question regarding gdb debugging a multi-thread program with python API.

In particular, I am wondering when a thread hits a breakpoint and execute the gdb python code of the breakpoint, is it feasible/safe to let it exit the breakpoint and re-enter the same breakpoint? What I would like to do is to work around the fact that in some situations "set scheduler-locking on" won't stop other threads when they hit a breakpoint. In case that happens (in fact, this happens a lot), I want them to quit, wait and re-enter their breakpoint. Do you think it is possible for gdb achieve that?

Thanks.

**Comment by kpouget** [comment]
Hello @mingwayzhang 
I don't really understand the problem you're facing, maybe you could illustrate it with a bit of code / log lines that would explain what's going wrong / what you expected?

what comes to my mind that might help you is something like this:

instead of 
```
def breakpoint(): # your original Py breakpoint function
   do_things() # crashes because not all the threads are stopped
   return False # don't stop
```

you do this:

```
def breakpoint(): # your original Py breakpoint function
     def do_at_prompt():
          # when this runs, the process is fully stopped
          do_things()
          gdb.event.before_prompt.disconnect(do_at_prompt)
     gdb.event.before_prompt.connect(do_at_prompt) # or something similar
     return True # tell GDB to correctly stop the process
```

this will execute `do_thinfs()` function in at a safe time, instead of during the breakpoint callback, where, as per the manual, you should not modify GDB internal state

hope this helps !

Kevin

**Comment by mingwayzhang** [comment]
Hi Kevin,

Thanks for your response! My problem is in fact a little different in that I need to "call a function in target program within my breakpoint code chunk".

I put reported one issue to gdb bug database as shown here:
https://sourceware.org/bugzilla/show_bug.cgi?id=23191

The question really is that: "I would like my gdb python script to automatically call a user function for each thread when they hit my breakpoint." There would be no interaction between gdb and user in my case. However, that seems not working even if the target user function is just a dummy empty function.

I tried scheduler-locking, it seems broken in that, whenever another thread hit the breakpoint, that thread would enter my critical code even if it does not have the lock.

I also tried post_event, i.e., putting all the code logic to post_event. That does not work either, since even if it is thread safe, by the time the post_event get executed, thread state might be "running" so, I cannot call a user function at that point.

I finally figure out that ONLY ONE thread could call my user function at a time. So what I did is the following: defining a global counter in gdb python. Since there is only one thread running at a time in gdb (unless you create more thread), checking this global counter could easily help a thread hitting my breakpoint to see if there is another thread suspended while holding the scheduler lock. So, I could ask him to leave. However, then that thread would not be able to execute the code logic that I expect. So, I need this thread to come back and re-enter the breakpoint until he has the chance to execute the code.

I might have said too much. Hope that clearly describe my problem. So far, what I can see is to figure out a way to let other threads re-enter the breakpoint. But if you could tell me alternative solutions, that would be excellent too!

Thanks
-Mingwei

**Comment by mingwayzhang** [comment]
Hi Kevin,

Regarding the gdb.event.before_prompt.connect(do_at_prompt) function. What could I do if want to continue the process instead of interacting with gdb through command line?

Thanks.
-Mingwei

**Comment by mingwayzhang** [comment]
Hi Kevin,

Problem solved! So basically by following your suggestion, letting the gdb going back to prompt, putting code in do_at_prompt and setting gdb to all-stop mode,  I could safely do stuff like calling user functions in multi-threading env with no problem. For automatic debuggin, I could use my bash script to feed gdb with my intended commands (which is always "continue" in my case) to continue the debugging process. So everything is running now!

An addition question on that is "is it safe to add a breakpoint in SIGSEGV handler?" I guess it is not, but if not, where is the right place to add breakpoints on signal?

Thanks
-Mingwei

**Comment by kpouget** [comment]
Hello Mingwei,

sorry I forgot to reply last time,

indeed, you figured it out, I was it the right direction with my first suggestion. You were facing two problems:

1. in `Breakpoint.stop`, you cannot do much, and it will crash gdb to execute some application functions. Hence the need to get out of this intermediate state, and go to a safe one: the prompt callback for instance. But you don't want to let the user interact with GDB at this point, so you finish the callback with something like `gdb.execute("continue")`.

2. when you execute application functions (`call test()` in the CLI, or its Python equivalent), by default GDB let all the threads run, not only the one executing the function. It's not fully intuitive, but that's the default behavior :)

for that, I've got a Python 'trick', see my [set_parameter](https://gitlab.inria.fr/dema/mcgdb/blob/b7c4b1640c6c1b25ea2fdd0eb804547d0d9266a1/toolbox/my_gdb.py#L750) function, which lets me write things like that:

```
with set_parameter("scheduler-locking", "on"):
              node = gdb.execute("p numa_node_of_cpu(sched_getcpu())", to_string=True)
```
and after exiting the `with` scope, the scheduler-locking with be reset to it's previous value


regards,

Kevin

**Comment by mingwayzhang** [comment]
Hi Kevin,

Thanks for you help! Sorry that I might have a remaining question. So does this connect/disconnect using pre_prompt event approach works for multiple breakpoints + signals? I mean, if I have multiple breakpoints (of different types) and one signal handler, in each of which I add such a do_at_prompt function. Does it work? I tried, but not entirely sure, since sometimes, my event got lost.

best
-Mingwei
